Updated to reflect new setup & added auto testing

diff --git a/.gitea/workflows/dev.yaml b/.gitea/workflows/dev.yaml
--- a/.gitea/workflows/dev.yaml
+++ b/.gitea/workflows/dev.yaml
@@ -8,58 +8,87 @@ jobs:
   release:
     name: Release
     steps:
-      - name: Build Image(s)
-        uses: https://${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/gitea-workflows-builder@main
+      - name: Build&Push Image
+        uses: https://${{ vars.LOCAL_REGISTRY_URL }}/${{ vars.LOCAL_REGISTRY_USERNAME }}/gitea-workflows-builder@main
         with:
-          registry_url: ${{ vars.LOCAL_ACR_URL }}
-          registry_username: ${{ vars.LOCAL_ACR_USERNAME }}
-          registry_password: ${{ secrets.LOCAL_ACR_PASSWORD }}
+          registry_url: ${{ vars.LOCAL_REGISTRY_URL }}
+          registry_username: ${{ vars.LOCAL_REGISTRY_USERNAME }}
+          registry_password: ${{ secrets.LOCAL_REGISTRY_PASSWORD }}
           development: true
 
-  # test:
-  #   name: Test
-  #   runs-on: ubuntu-latest
-  #   container:
-  #     image: catthehacker/ubuntu:act-latest
-  #   steps:
-  #     - name: Run container and capture logs
-  #       env:
-  #         SWITCH_HOST: 
-  #         SWITCH_USERNAME: 
-  #         SWITCH_PASSWORD: 
-  #         SFTP_HOST: 
-  #         SFTP_USERNAME: 
-  #         SFTP_PASSWORD: 
-  #         SFTP_PATH: 
-  #         PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER }}
-  #         PUSHOVER_APP_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
-  #       run: |
-  #         docker run --name test ${{ env.IMAGE_BASE }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.DATE_RELEASE }}${{ env.IMAGE_TAG_ENDING }} /bin/bash -c "/app/setup.sh; /app/run.sh"
-  #         docker wait test
-  #         docker logs test > logs.txt
-  #         docker rm test
+  test:
+    name: Test
+    needs: 
+      - release
+    runs-on: ubuntu-latest
+    container:
+      image: catthehacker/ubuntu:act-latest
+    steps:
+      - name: Get Meta
+        id: meta
+        run: |
+          echo REPO_NAME=$(echo "${GITHUB_REPOSITORY##*/}") >> $GITHUB_OUTPUT
+          echo DATE_RELEASE=$(echo "`date +'%Y.%m.%d'`") >> $GITHUB_OUTPUT
 
-  #     - name: Send Logs via Email
-  #       uses: dawidd6/action-send-mail@v6
-  #       with:
-  #         connection_url: ${{ secrets.SMTP_CONNECTION }}
-  #         subject: 
-  #         to: ${{ vars.SMTP_RECEIVER }}
-  #         from: Gitea DevOps - Test Results for ${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.DATE_RELEASE }}${{ env.IMAGE_TAG_ENDING }}
-  #         body: Please see attached logs file.
-  #         attachments: logs.txt
+      - name: Run Container & Capture Logs
+        run: |
+          CONTAINER_NAME="${{ steps.meta.outputs.REPO_NAME }}-auto-test"
+          if docker ps -a --filter "name=$CONTAINER_NAME" --format "{{.ID}}" | grep -q .; then
+            echo "Stopping and removing existing container: $CONTAINER_NAME..."
+            docker stop $CONTAINER_NAME
+            docker rm -f $CONTAINER_NAME
+          fi
+          docker pull ${{ vars.LOCAL_REGISTRY_URL }}/${{ vars.LOCAL_REGISTRY_USERNAME }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.DATE_RELEASE }}-dev
+          docker run --name $CONTAINER_NAME \
+            -e SYNOLOGY_HOST=${{ vars.SYNOLOGY_HOST }} \
+            -e SYNOLOGY_USERNAME=${{ vars.SYNOLOGY_USERNAME }} \
+            -e SYNOLOGY_PASSWORD=${{ secrets.SYNOLOGY_PASSWORD }} \
+            -e SFTP_HOST=${{ vars.SFTP_HOST }} \
+            -e SFTP_USERNAME=${{ vars.SFTP_USERNAME }} \
+            -e SFTP_PASSWORD=${{ secrets.SFTP_PASSWORD }} \
+            -e SFTP_PATH="/backup/network_configs__TEST" \
+            -e PUSHOVER_USER_KEY=${{ secrets.PUSHOVER_USER }} \
+            -e PUSHOVER_APP_TOKEN=${{ secrets.PUSHOVER_TOKEN }} \
+            ${{ vars.LOCAL_REGISTRY_URL }}/${{ vars.LOCAL_REGISTRY_USERNAME }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.DATE_RELEASE }}-dev \
+            bash -c "/app/setup.sh && /app/run.sh"
+          docker wait $CONTAINER_NAME
+          docker rm $CONTAINER_NAME
+
+      - name: Check If Backup File Exists in SFTP
+        env:
+          SFTP_HOST: ${{ vars.SFTP_HOST }}
+          SFTP_USERNAME: ${{ vars.SFTP_USERNAME }}
+          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
+          BACKUP_PATH: /backup/network_configs__TEST
+          BACKUP_FILE: ${{ vars.SYNOLOGY_HOST }}__config__${{ steps.meta.outputs.DATE_RELEASE }}.dss
+        run: |
+          apt update; apt install sshpass -y
+          sshpass -p "$SFTP_PASSWORD" sftp -oBatchMode=no -oStrictHostKeyChecking=no -b - $SFTP_USERNAME@$SFTP_HOST <<EOF
+          ls $BACKUP_PATH/$BACKUP_FILE
+          EOF
+          if [ $? -eq 0 ]; then
+            echo "Backup file found in SFTP endpoint!"
+            exit 0
+          else
+            echo "Backup file not found in SFTP endpoint!"
+            exit 1
+          fi
 
   report:
     name: Report
+    if: always()
     continue-on-error: true
-    needs: 
+    needs:
       - release
-      # - test
+      - test
+    env:
+      SUCCESS: ${{ needs.release.result == 'success' && needs.test.result == 'success' }}
     steps:
       - name: Notify User
-        uses: https://${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/gitea-workflows-notification@main
+        uses: https://${{ vars.LOCAL_REGISTRY_URL }}/${{ vars.LOCAL_REGISTRY_USERNAME }}/gitea-workflows-notification@main
         with:
-          success: needs.release.result == 'success' # && needs.test.result == 'success'
+          success: ${{ env.SUCCESS }}
           development: true
+          tested: true
           pushover_user: ${{ secrets.PUSHOVER_USER }}
           pushover_token: ${{ secrets.PUSHOVER_TOKEN }}
